// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.ColorBrightnessCalculator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("hex")]
        public string Hex { get; set; }

        [JsonProperty("rgb")]
        public Rgb Rgb { get; set; }

        [JsonProperty("luminance")]
        public double Luminance { get; set; }

        [JsonProperty("perceived_brightness")]
        public long PerceivedBrightness { get; set; }

        [JsonProperty("yiq")]
        public double Yiq { get; set; }

        [JsonProperty("is_light")]
        public bool IsLight { get; set; }

        [JsonProperty("is_dark")]
        public bool IsDark { get; set; }

        [JsonProperty("brightness_category")]
        public string BrightnessCategory { get; set; }

        [JsonProperty("recommended_text_color")]
        public string RecommendedTextColor { get; set; }

        [JsonProperty("contrast_ratio_with_white")]
        public double ContrastRatioWithWhite { get; set; }

        [JsonProperty("contrast_ratio_with_black")]
        public double ContrastRatioWithBlack { get; set; }

        [JsonProperty("wcag_aa_compliant_with_white")]
        public bool WcagAaCompliantWithWhite { get; set; }

        [JsonProperty("wcag_aa_compliant_with_black")]
        public bool WcagAaCompliantWithBlack { get; set; }

        [JsonProperty("wcag_aaa_compliant_with_white")]
        public bool WcagAaaCompliantWithWhite { get; set; }

        [JsonProperty("wcag_aaa_compliant_with_black")]
        public bool WcagAaaCompliantWithBlack { get; set; }
    }

    public partial class Rgb
    {
        [JsonProperty("r")]
        public long R { get; set; }

        [JsonProperty("g")]
        public long G { get; set; }

        [JsonProperty("b")]
        public long B { get; set; }
    }
}
